export const HANDLE_FAVORITE='HANDLE_FAVORITE';
export const ADD_QUEUE='ADD_QUEUE';
export const FETCHING_VIDEOS='FETCHING_VIDEOS';
export const FETCHING_VIDEOS_SUCCESS='FETCHING_VIDEOS_SUCCESS';
export const FETCHING_VIDEOS_ERROR='FETCHING_VIDEOS_ERROR';
export const LOAD_VIDEOS='LOAD_VIDEOS';
export const PLAY_SONG='PLAY_SONG';
export const HANDLE_PLAY_SONG='HANDLE_PLAY_SONG';
